import        SideBar            from '@/components/SideBar';
import                                './globals.css';
import type { Metadata }         from 'next';
import      { Inter }            from 'next/font/google';
import        Head               from './head';
import      { getServerSession } from "next-auth";
import      { SessionProvider }  from '@/components/SessionProvider';
import      { authOptions }      from '@/pages/api/auth/[...nextauth]';
import        Login              from '@/components/Login';
import ClientProvider from '@/components/ClientProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
        title: 'ChatGPT Clone Messenger - Nextjs & Reactjs',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <Head />
      <body>
        <SessionProvider session={session}> 
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              {/* <SIDEBAR> */}
              <div className="bg-[#ffffff] max-w-xs h-screen overflow-y-scroll md:min-w-[20rem]">            
                <SideBar />
              </div>
              {/* <.SIDEBAR> */}

              {/*<ClientProvider - Notification>*/}
              <ClientProvider />
              {/*<.ClientProvider - Notification>*/}

              <div className="bg-[#ffffff] flex-1">          
                {children}
              </div>    
            </div>
          )}       
        </SessionProvider>
      </body>
    </html>
  )
}
